#!/usr/bin/env python3
"""
makeTables.py - generate the LaTeX tables for the elasticity block-encoding paper.

Place in the repository root (next to pyblockencode/) and run:

    python makeTables.py                 # tables/*.tex, gate counts to m = 6
    python makeTables.py --mmax 8        # push the scaling table further
    python makeTables.py --no-legacy     # skip the slow MCX-ladder column

Writes into ./tables/ :

    tab_lcu.tex           the 17 LCU terms, generated from lcu_terms()
    tab_resources.tex     resource summary for the encoding
    tab_gatecounts.tex    measured T / Toffoli / depth vs m, both constructions
    tab_verification.tex  block-encoding errors, Poisson and elasticity

Every number is computed, never transcribed, so the tables cannot drift from
the code.  Each file is a bare \\begin{table}...\\end{table} meant to be
\\input{} from the manuscript; none of them emit \\documentclass or preamble.

Expensive transpilation results are cached in .paper_cache.json and shared
with makeFigures.py.  Delete that file to force recomputation.
"""
from __future__ import annotations

import argparse
import json
import math
import os
import sys
import time

import numpy as np

TABLES = "tables"
CACHE = ".paper_cache.json"

# Clifford+T.  rz survives from the constant-size PREP state preparation and
# does not affect the scaling.
BASIS = ['h', 't', 'tdg', 's', 'sdg', 'x', 'z', 'cx', 'rz']


# ---------------------------------------------------------------------------
# cache shared with makeFigures.py
# ---------------------------------------------------------------------------

def cache_load() -> dict:
    if os.path.exists(CACHE):
        try:
            with open(CACHE) as f:
                return json.load(f)
        except Exception:
            pass
    return {}


def cache_save(d: dict) -> None:
    with open(CACHE, 'w') as f:
        json.dump(d, f, indent=1, sort_keys=True)


# ---------------------------------------------------------------------------
# LaTeX helpers
# ---------------------------------------------------------------------------

def fnum(x, nd=4):
    """Fixed-point with an explicit sign, for coefficient columns."""
    return f"{x:+.{nd}f}"


def sci(x, nd=1):
    """Scientific notation as LaTeX math, e.g. 3.8\\times10^{-16}."""
    if x == 0:
        return "0"
    e = int(math.floor(math.log10(abs(x))))
    mant = x / 10 ** e
    return rf"${mant:.{nd}f}\times10^{{{e}}}$"


def thousands(n):
    return f"{int(n):,}".replace(",", r"\,")


HEADER = ("%% GENERATED BY makeTables.py -- DO NOT EDIT BY HAND.\n"
          "%% Regenerate with:  python makeTables.py\n")


def write(name: str, body: str) -> None:
    os.makedirs(TABLES, exist_ok=True)
    path = os.path.join(TABLES, name)
    with open(path, 'w') as f:
        f.write(HEADER + body)
    print(f"  wrote {path}")


# ---------------------------------------------------------------------------
# Table 1 - the 17 LCU terms
# ---------------------------------------------------------------------------

SYM = {'I': r'$I$', 'Sc': r'$S$', 'Scd': r'$S^\dagger$',
       'X': r'$X$', 'Z': r'$Z$'}

# Print the terms grouped by DOF channel, and inside a channel in a stable
# order, so the table is reproducible run to run.
ORDER = {'I': 0, 'Sc': 1, 'Scd': 2}


def table_lcu(nu: float = 0.3) -> None:
    from pyblockencode.elasticity_pattern import ElasticityPatternEncoding
    enc = ElasticityPatternEncoding(m=3, E=1.0, nu=nu)
    terms = enc.lcu_terms()

    def key(k):
        xl, yl, dl = k
        return ({'I': 0, 'Z': 1, 'X': 2}[dl], ORDER[xl], ORDER[yl])

    rows = []
    for k in sorted(terms, key=key):
        xl, yl, dl = k
        rows.append(f"{SYM[xl]} & {SYM[yl]} & {SYM[dl]} & ${fnum(terms[k])}$ \\\\")

    # count how many terms each channel contributes
    nI = sum(1 for k in terms if k[2] == 'I')
    nZ = sum(1 for k in terms if k[2] == 'Z')
    nX = sum(1 for k in terms if k[2] == 'X')

    body = rf"""\begin{{table}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{4pt}}
\renewcommand{{\arraystretch}}{{1.15}}
\caption{{The {len(terms)} LCU terms of the plane-stress $Q_4$ elasticity operator
($E=1$, $\nu={nu}$), grouped by DOF channel.  With $a^K$, $b^M$, $g$ the
cyclic-shift coefficients of $\mathbf{{K}}_1$, $\mathbf{{M}}_1$, $\mathbf{{G}}_1$
from Eqs.~\eqref{{eq:K1-shift}}--\eqref{{eq:G1-shift}}, the coefficients are
$c_{{pqI}} = C\frac{{3-\nu}}{{4}}(a^K_p b^M_q + b^M_p a^K_q)$,
$c_{{pqZ}} = C\frac{{1+\nu}}{{4}}(a^K_p b^M_q - b^M_p a^K_q)$ and
$c_{{pqX}} = -C\frac{{1+\nu}}{{2}} g_p g_q$.
The $Z$ channel is antisymmetric under $p\leftrightarrow q$, so it vanishes on the
three diagonal pairs and on $(S,S^\dagger)$, $(S^\dagger,S)$, leaving {nZ} of 9
terms; with {nI} in the $I$ channel and {nX} in the $X$ channel the total is
{len(terms)}, independent of $\nu$ and $N$.}}
\label{{tab:lcu}}
\begin{{tabular}}{{@{{}}lllr@{{}}}}
\toprule
$V_x$ & $V_y$ & $\sigma_{{\mathrm{{dof}}}}$ & coefficient \\
\midrule
{chr(10).join(rows)}
\midrule
\multicolumn{{3}}{{@{{}}l}}{{$\alpha = \sum|c_{{pqr}}|$}} & ${enc.alpha:.4f}$ \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("tab_lcu.tex", body)


# ---------------------------------------------------------------------------
# Table 2 - resource summary
# ---------------------------------------------------------------------------

def table_resources(gc: dict) -> None:
    from pyblockencode.elasticity_pattern import ElasticityPatternEncoding
    from pyblockencode import operators

    a0 = ElasticityPatternEncoding(m=3, nu=0.0).alpha
    a3 = ElasticityPatternEncoding(m=3, nu=0.3).alpha
    a45 = ElasticityPatternEncoding(m=3, nu=0.45).alpha

    ms = sorted(int(k) for k in gc)
    if len(ms) >= 2:
        m1, m2 = ms[-2], ms[-1]
        slope = gc[str(m2)]['new_t'] - gc[str(m1)]['new_t']
        icept = gc[str(m2)]['new_t'] - slope * m2
        tfit = rf"${int(slope)}\,m {icept:+d}$"
    else:
        tfit = "---"

    body = rf"""\begin{{table}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\renewcommand{{\arraystretch}}{{1.15}}
\caption{{Resources for the pattern-compression block encoding of the 2D
plane-stress $Q_4$ elasticity operator ($E=1$), on an $N\times N$ grid with
$N=2^m$.  The $T$-count is measured by transpiling the circuit to a Clifford$+T$
basis, not inferred from a citation.}}
\label{{tab:resources}}
\begin{{tabular}}{{@{{}}ll@{{}}}}
\toprule
Quantity & Value \\
\midrule
System qubits            & $2m+1$ \\
Ancilla qubits           & $m+7$ \\
\quad PREP / flag / control / carry & $5$ / $2$ / $1$ / $m-1$ \\
Total qubits             & $\mathbf{{3m+8}}$ \\
LCU terms $L$            & $17$ (constant in $N$) \\
Subnormalization $\alpha$ & $\dfrac{{E(33+\nu)}}{{6(1-\nu^2)}}$ \ (constant in $N$) \\[4pt]
                         & ${a0:.3f}$ / ${a3:.3f}$ / ${a45:.3f}$ at $\nu = 0$ / $0.3$ / $0.45$ \\
$\alpha/\norm{{\mathbf{{K}}}}$ & $\to (33+\nu)/24 \in [1.375,\,1.40]$ \\
$T$-count                & {tfit} \ (measured, $\mathcal{{O}}(\log N)$) \\
Circuit depth            & $\mathcal{{O}}(m) = \mathcal{{O}}(\log N)$ \\
Boundary conditions      & homogeneous Dirichlet \\
\quad enforced by            & one wrap flag per register \\
Verification error       & $\sim10^{{-13}}$ (see Table~\ref{{tab:verification}}) \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("tab_resources.tex", body)


# ---------------------------------------------------------------------------
# Table 3 - measured gate counts
# ---------------------------------------------------------------------------

def collect_gatecounts(mmax: int, legacy: bool, cache: dict) -> dict:
    from qiskit import transpile
    from pyblockencode.linear_circuits import LinearElasticityCircuit
    from pyblockencode.qiskit_encoding import ElasticityCircuit

    gc = cache.get('gatecounts', {})
    for m in range(2, mmax + 1):
        rec = gc.get(str(m), {})
        need_new = 'new_t' not in rec
        need_old = legacy and 'old_t' not in rec
        if not (need_new or need_old):
            continue
        print(f"  transpiling m={m} ...", end='', flush=True)
        t0 = time.time()
        if need_new:
            n = LinearElasticityCircuit(m=m, nu=0.3)
            tq = transpile(n.circuit(), basis_gates=BASIS, optimization_level=1)
            ops = tq.count_ops()
            rec['new_t'] = ops.get('t', 0) + ops.get('tdg', 0)
            rec['new_cx'] = ops.get('cx', 0)
            rec['new_depth'] = tq.depth()
            rec['new_qubits'] = n.num_qubits
        if need_old:
            o = ElasticityCircuit(m=m, nu=0.3)
            tq = transpile(o.circuit(), basis_gates=BASIS, optimization_level=1)
            ops = tq.count_ops()
            rec['old_t'] = ops.get('t', 0) + ops.get('tdg', 0)
            rec['old_cx'] = ops.get('cx', 0)
            rec['old_depth'] = tq.depth()
            rec['old_qubits'] = o.num_qubits
        gc[str(m)] = rec
        print(f" {time.time()-t0:.1f}s")
    cache['gatecounts'] = gc
    cache_save(cache)
    return gc


def table_gatecounts(gc: dict, legacy: bool) -> None:
    ms = sorted(int(k) for k in gc)
    rows = []
    for m in ms:
        r = gc[str(m)]
        if legacy and 'old_t' in r:
            ratio = r['old_t'] / max(r['new_t'], 1)
            rows.append(
                f"${m}$ & ${2**m}$ & {thousands(r['old_t'])} & ${r['old_qubits']}$ & "
                f"{thousands(r['new_t'])} & {thousands(r['new_depth'])} & "
                f"${r['new_qubits']}$ & ${ratio:.0f}\\times$ \\\\")
        else:
            rows.append(
                f"${m}$ & ${2**m}$ & --- & --- & {thousands(r['new_t'])} & "
                f"{thousands(r['new_depth'])} & ${r['new_qubits']}$ & --- \\\\")

    body = rf"""\begin{{table*}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{6pt}}
\renewcommand{{\arraystretch}}{{1.15}}
\caption{{Measured non-Clifford cost of the elasticity block encoding ($\nu=0.3$),
after transpilation to a Clifford$+T$ basis.  ``MCX ladder'' is the incrementer
built from multi-controlled $X$ gates with $0,\dots,m-1$ controls, the
construction used in the reference implementation of Kharazi
et~al.~\cite{{kharazi2025explicit}}; ``linear'' is the prefix-AND incrementer of
Section~\ref{{sec:encoding}}, which uses $m-1$ additional ancillas.  The linear
$T$-count is exactly affine in $m$, so the $\mathcal{{O}}(\log N)$ claim is
measured rather than inherited by citation.}}
\label{{tab:gatecounts}}
\begin{{tabular}}{{@{{}}rr rr rrr r@{{}}}}
\toprule
& & \multicolumn{{2}}{{c}}{{MCX ladder}} & \multicolumn{{3}}{{c}}{{Linear incrementer}} & \\
\cmidrule(lr){{3-4}}\cmidrule(lr){{5-7}}
$m$ & $N$ & $T$ & qubits & $T$ & depth & qubits & speedup \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\end{{table*}}
"""
    write("tab_gatecounts.tex", body)


# ---------------------------------------------------------------------------
# Table 4 - verification
# ---------------------------------------------------------------------------

def collect_verification(cache: dict) -> list:
    from pyblockencode.linear_circuits import (
        LinearElasticityCircuit, LinearPoissonCircuit, verify_columns)

    rows = cache.get('verification')
    if rows:
        return rows
    rows = []
    cases = [("elasticity, $\\nu=0$", lambda: LinearElasticityCircuit(m=2, nu=0.0)),
             ("elasticity, $\\nu=0.3$", lambda: LinearElasticityCircuit(m=2, nu=0.3)),
             ("elasticity, $\\nu=0.45$", lambda: LinearElasticityCircuit(m=2, nu=0.45)),
             ("Poisson 1D, FDM", lambda: LinearPoissonCircuit(m=4, dim=1, disc='fdm')),
             ("Poisson 1D, FEM", lambda: LinearPoissonCircuit(m=4, dim=1, disc='fem')),
             ("Poisson 2D, FDM", lambda: LinearPoissonCircuit(m=3, dim=2, disc='fdm')),
             ("Poisson 2D, FEM", lambda: LinearPoissonCircuit(m=3, dim=2, disc='fem'))]
    for label, mk in cases:
        enc = mk()
        print(f"  verifying {label} ...", end='', flush=True)
        t0 = time.time()
        r = verify_columns(enc)
        rows.append({'label': label, 'm': enc.m, 'qubits': r['num_qubits'],
                     'N0': r['N0'], 'err': r['block_encoding_rel_err']})
        print(f" {r['block_encoding_rel_err']:.1e}  ({time.time()-t0:.1f}s)")
    cache['verification'] = rows
    cache_save(cache)
    return rows


def table_verification(rows: list) -> None:
    body_rows = [
        f"{r['label']} & ${r['m']}$ & ${r['N0']}$ & ${r['qubits']}$ & {sci(r['err'])} \\\\"
        for r in rows]
    body = rf"""\begin{{table}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\renewcommand{{\arraystretch}}{{1.15}}
\caption{{Block-encoding verification.  Each column of
$\alpha\,U[{{:}}N_0,{{:}}N_0]$ is obtained by a separate statevector simulation
and compared against the classically assembled operator; the table reports the
relative Frobenius error.  Column-wise simulation costs $2^{{n_q}}$ rather than
the $4^{{n_q}}$ of forming the dense unitary, which is what makes the larger
cases reachable.}}
\label{{tab:verification}}
\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\toprule
Operator & $m$ & $N_0$ & qubits & rel.\ error \\
\midrule
{chr(10).join(body_rows)}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("tab_verification.tex", body)


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--mmax', type=int, default=6,
                    help='largest m in the gate-count table (default 6)')
    ap.add_argument('--nu', type=float, default=0.3)
    ap.add_argument('--no-legacy', action='store_true',
                    help='skip the MCX-ladder column (it is the slow one)')
    ap.add_argument('--no-verify', action='store_true',
                    help='skip the verification table (statevector sims)')
    args = ap.parse_args()

    try:
        import pyblockencode  # noqa: F401
    except ImportError:
        sys.exit("Run this from the repository root (the folder holding "
                 "pyblockencode/).")

    cache = cache_load()
    legacy = not args.no_legacy

    print("LCU terms ...")
    table_lcu(args.nu)

    print("gate counts ...")
    gc = collect_gatecounts(args.mmax, legacy, cache)
    table_gatecounts(gc, legacy)

    print("resources ...")
    table_resources(gc)

    if not args.no_verify:
        print("verification ...")
        table_verification(collect_verification(cache))

    print(f"\nDone.  \\input{{tables/...}} from the manuscript.")


if __name__ == '__main__':
    main()