#!/usr/bin/env python3
"""
makeTables.py - generate the LaTeX tables for the elasticity block-encoding paper.

Place in the repository root (next to pyblockencode/) and run:

    python makeTables.py                 # tables/*.tex, gate counts to m = 6
    python makeTables.py --mmax 8        # push the scaling table further
    python makeTables.py --mcx           # add the MCX-ladder comparison column

The MCX-ladder column is opt-in because it is the expensive half of the run:
its T-count is superlinear in m where the linear incrementer is affine, so it
costs 46s at m = 4 and grows fast.  Pass --mcx when regenerating the table for
the manuscript; without it those columns are dashed out.

Writes into ./tables/ :

    tab_lcu.tex           the 17 periodic LCU terms, from lcu_terms()
    tab_boundary.tex      L, alpha and components under each boundary treatment
    tab_resources.tex     resource summary for the encoding
    tab_gatecounts.tex    measured T / Toffoli / depth vs m, both constructions
    tab_verification.tex  block-encoding errors, Poisson and elasticity

Every number is computed, never transcribed, so the tables cannot drift from
the code.  Each file is a bare \\begin{table}...\\end{table} meant to be
\\input{} from the manuscript; none of them emit \\documentclass or preamble.

Nothing is cached: every run transpiles from scratch.  A cache is the wrong
trade here, because it silently survives a change to the encoders and hands
back gate counts for circuits that no longer exist.  Use --mmax to bound the
cost instead.
"""
from __future__ import annotations

import argparse
import math
import os
import sys
import time

import numpy as np

TABLES = "tables"

# Clifford+T.  rz survives from the constant-size PREP state preparation and
# does not affect the scaling.
BASIS = ['h', 't', 'tdg', 's', 'sdg', 'x', 'z', 'cx', 'rz']


# ---------------------------------------------------------------------------
# LaTeX helpers
# ---------------------------------------------------------------------------

def fnum(x, nd=4):
    """Fixed-point with an explicit sign, for coefficient columns."""
    return f"{x:+.{nd}f}"


def sci(x, nd=1):
    """Scientific notation as LaTeX math, e.g. 3.8\\times10^{-16}."""
    if x == 0:
        return "0"
    e = int(math.floor(math.log10(abs(x))))
    mant = x / 10 ** e
    return rf"${mant:.{nd}f}\times10^{{{e}}}$"


def thousands(n):
    return f"{int(n):,}".replace(",", r"\,")


HEADER = ("%% GENERATED BY makeTables.py -- DO NOT EDIT BY HAND.\n"
          "%% Regenerate with:  python makeTables.py\n")


def write(name: str, body: str) -> None:
    os.makedirs(TABLES, exist_ok=True)
    path = os.path.join(TABLES, name)
    with open(path, 'w') as f:
        f.write(HEADER + body)
    print(f"  wrote {path}")


# ---------------------------------------------------------------------------
# Table 1 - the 17 LCU terms
# ---------------------------------------------------------------------------

# The unitary set of bc.py: three labels for the periodic operator, five once
# essential conditions split each shift, seven with traction-free corrections.
SYM = {'I': r'$I$',
       'Sc': r'$S$', 'R0.Sc': r'$R_0 S$',
       'Scd': r'$S^\dagger$', 'RN.Scd': r'$R_{N-1} S^\dagger$',
       'R0': r'$R_0$', 'RN': r'$R_{N-1}$',
       'X': r'$X$', 'Z': r'$Z$', 'iY': r'$iY$'}

# Print the terms grouped by Pauli component, and inside a component in a
# stable order, so the table is reproducible run to run.
ORDER = {'I': 0, 'Sc': 1, 'R0.Sc': 2, 'Scd': 3, 'RN.Scd': 4,
         'R0': 5, 'RN': 6}
COMP_ORDER = {'I': 0, 'Z': 1, 'X': 2, 'iY': 3}


def table_lcu(nu: float = 0.3) -> None:
    """Table 1: the 17 periodic LCU terms, grouped by coefficient.

    Seventeen terms carry only four distinct magnitudes.  The grouping is
    asserted rather than assumed, so if the decomposition ever changes the
    table fails loudly instead of printing a wrong caption.
    """
    from pyblockencode.elasticity_pattern import ElasticityPatternEncoding

    # Table 1 of the paper is Proposition 1: the periodic operator, before
    # any boundary treatment splits the shifts.
    enc = ElasticityPatternEncoding(m=3, E=1.0, nu=nu, bc='periodic')
    terms = enc.lcu_terms()
    assert len(terms) == 17, f"expected the 17 periodic terms, got {len(terms)}"

    def group(key):
        p_, q_, sg = key
        if sg == 'I':
            return 'Ic' if (p_, q_) == ('I', 'I') else 'In'
        return sg + ('+' if terms[key] > 0 else '-')

    groups: dict = {}
    for k in terms:
        groups.setdefault(group(k), []).append(k)

    # every member of a group must share one coefficient
    for g, ks in groups.items():
        vals = [terms[k] for k in ks]
        assert max(vals) - min(vals) < 1e-13, f"group {g} is not uniform"

    # closed forms at E = 1, keyed by group; checked against the encoder below
    C = 1.0 / (1.0 - nu ** 2)
    closed = {
        'Ic': (r'$\dfrac{2(3-\nu)}{3(1-\nu^{2})}$', 2 * (3 - nu) / 3 * C),
        'In': (r'$-\dfrac{3-\nu}{12(1-\nu^{2})}$', -(3 - nu) / 12 * C),
        'Z+': (r'$+\dfrac{1}{4(1-\nu)}$', 1 / (4 * (1 - nu))),
        'Z-': (r'$-\dfrac{1}{4(1-\nu)}$', -1 / (4 * (1 - nu))),
        'X+': (r'$+\dfrac{1}{8(1-\nu)}$', 1 / (8 * (1 - nu))),
        'X-': (r'$-\dfrac{1}{8(1-\nu)}$', -1 / (8 * (1 - nu))),
    }
    for g, ks in groups.items():
        assert abs(closed[g][1] - terms[ks[0]]) < 1e-13, \
            f"closed form for {g} disagrees with the encoder"

    def offsets(g):
        if g == 'Ic':
            return r'$(I,I)$, the centre'
        if g == 'In':
            return 'all eight neighbours'
        return ', '.join(f'$({SYM[a][1:-1]},{SYM[b][1:-1]})$'
                         for a, b, _ in sorted(groups[g]))

    order = ['Ic', 'In', 'Z+', 'Z-', 'X+', 'X-']
    rows = []
    for g in order:
        ks = groups[g]
        sym_dof = SYM[ks[0][2]]
        rows.append(f"{sym_dof} & {offsets(g)} & ${len(ks)}$ & "
                    f"{closed[g][0]} & ${terms[ks[0]]:+.4f}$ \\\\")

    body = rf"""\begin{{table}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\renewcommand{{\arraystretch}}{{1.45}}
\caption{{The {len(terms)} LCU terms of the plane-stress $Q_4$ elasticity
operator at $E = 1$, grouped by coefficient.  $S \equiv \Sc$,
$S^\dagger \equiv \Scd$, and the shift pair $(V_x, V_y)$ names the stencil
offset.  {len(terms)} terms carry only {len(order)-2} distinct magnitudes: the
$I$ component takes one value at the centre and a single common value on all
eight neighbours, because $a^K_p b^M_q + b^M_p a^K_q = -\tfrac13$ for every
pair but $(I,I)$.  In the $Z$ and $X$ components the factor $(1+\nu)$ cancels
against $C = E/(1-\nu^2)$, so those weights depend on $\nu$ only through
$1/(1-\nu)$.  Summing the four magnitudes with their multiplicities gives
$\alpha(\nu)$ in~\eqref{{eq:alpha}}.}}
\label{{tab:lcu}}
\begin{{tabular}}{{@{{}}llccr@{{}}}}
\toprule
$\sigma_{{\mathrm{{dof}}}}$ & stencil offsets $(V_x,V_y)$ & \# &
  coefficient & $\nu={nu}$ \\
\midrule
{chr(10).join(rows)}
\midrule
\multicolumn{{2}}{{@{{}}l}}{{$\alpha = \sum_k |c_k|$}} & ${len(terms)}$
    & $\dfrac{{E(33+\nu)}}{{6(1-\nu^{{2}})}}$ & ${enc.alpha:.4f}$ \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("tab_lcu.tex", body)


# ---------------------------------------------------------------------------
# Table - boundary treatments
# ---------------------------------------------------------------------------

def table_boundary(nu: float = 0.3) -> None:
    """L, alpha and the Pauli components under each boundary treatment."""
    from pyblockencode.elasticity_pattern import ElasticityPatternEncoding

    cases = [
        ("none (periodic)", "periodic"),
        ("all four (essential)", "essential"),
        ("left and right", [("clamped", "clamped"), ("free", "free")]),
        ("left only", [("clamped", "free"), ("free", "free")]),
        ("none (traction-free)", "free"),
    ]
    rows = []
    for label, spec in cases:
        e = ElasticityPatternEncoding(m=3, E=1.0, nu=nu, bc=spec)
        comps = ", ".join(SYM[c] for c in e.components)
        rows.append(f"{label} & {comps} & ${e.num_terms}$ & "
                    f"${e.alpha:.3f}$ & ${e.num_qubits}$ \\\\")

    e13 = ElasticityPatternEncoding(m=3, E=1.0, nu=1 / 3, bc="free")

    body = rf"""\begin{{table}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\renewcommand{{\arraystretch}}{{1.15}}
\caption{{Boundary treatments for the plane-stress $Q_4$ elasticity operator
($E=1$, $\nu={nu}$), on an $N\times N$ grid with $N=2^m$.  Unlisted edges are
traction-free.  Conditions are imposed by adjoining reflections to the unitary
set, so no case needs a flag qubit and $\alpha$ never exceeds the
traction-free value.  The $iY$ component appears as soon as one direction
carries a diagonal correction, so clamping two opposite edges already requires
four components rather than three.  At $\nu=1/3$ the $iY$ coefficient
$(1-3\nu)/4$ vanishes and the traction-free count drops to ${e13.num_terms}$.
All rows are independent of $N$ and verified against a direct $Q_4$ assembly.}}
\label{{tab:boundary}}
\begin{{tabular}}{{@{{}}llrrr@{{}}}}
\toprule
Edges clamped & Pauli components & $L$ & $\alpha$ & qubits \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("tab_boundary.tex", body)


# ---------------------------------------------------------------------------
# Table 2 - resource summary
# ---------------------------------------------------------------------------

def table_resources(gc: dict) -> None:
    from pyblockencode.elasticity_pattern import ElasticityPatternEncoding
    from pyblockencode.linear_circuits import LinearElasticityCircuit

    a0 = ElasticityPatternEncoding(m=3, nu=0.0).alpha
    a3 = ElasticityPatternEncoding(m=3, nu=0.3).alpha
    a45 = ElasticityPatternEncoding(m=3, nu=0.45).alpha

    per = ElasticityPatternEncoding(m=3, nu=0.3, bc='periodic')
    ess = ElasticityPatternEncoding(m=3, nu=0.3, bc='essential')
    fre = ElasticityPatternEncoding(m=3, nu=0.3, bc='free')

    # abstract LCU accounting, and the extra ancillas the linear-depth
    # implementation asks for on top of it
    lin = LinearElasticityCircuit(m=3, nu=0.3)

    ms = sorted(int(k) for k in gc)
    if len(ms) >= 2:
        m1, m2 = ms[-2], ms[-1]
        slope = gc[str(m2)]['new_t'] - gc[str(m1)]['new_t']
        icept = gc[str(m2)]['new_t'] - slope * m2
        tfit = rf"${int(slope)}\,m {icept:+d}$"
    else:
        tfit = "---"

    body = rf"""\begin{{table}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\renewcommand{{\arraystretch}}{{1.15}}
\caption{{Resources for the shift-decomposition block encoding of the 2D
plane-stress $Q_4$ elasticity operator ($E=1$) with essential boundary
conditions, on an $N\times N$ grid with $N=2^m$.  Boundary conditions are
carried by reflections adjoined to the unitary set, so the ancilla register is
PREP only.  The $T$-count is measured by transpiling the circuit to a
Clifford$+T$ basis, not inferred from a citation.}}
\label{{tab:resources}}
\begin{{tabular}}{{@{{}}ll@{{}}}}
\toprule
Quantity & Value \\
\midrule
System qubits            & $2m+1$ \\
PREP ancilla             & $\lceil\log_2 {ess.num_terms}\rceil = {ess.num_ancilla}$ \\
Flag ancilla             & none \\
Total qubits             & $\mathbf{{2m+{ess.num_qubits - 6}}}$ \\
\quad linear-depth variant   & $+m$ (control $+$ $m-1$ carry) $= 3m+{lin.num_qubits - 9}$ \\
LCU terms $L$            & ${per.num_terms}$ periodic / ${ess.num_terms}$ essential /
                           ${fre.num_terms}$ traction-free (constant in $N$) \\
Pauli components         & $I,Z,X$ \ ($+\,iY$ when a direction is free) \\
Subnormalization $\alpha$ & $\dfrac{{E(33+\nu)}}{{6(1-\nu^2)}}$ \ (constant in $N$) \\[4pt]
                         & ${a0:.3f}$ / ${a3:.3f}$ / ${a45:.3f}$ at $\nu = 0$ / $0.3$ / $0.45$ \\
$\alpha/\norm{{\mathbf{{K}}}}_2$ & $\to (33+\nu)/24 \in [1.375,\,1.40]$ \\
$\alpha/\norm{{\mathbf{{K}}}}_\infty$ & $\approx 1.18$--$1.22$ \\
$T$-count                & {tfit} \ (measured, $\mathcal{{O}}(\log N)$) \\
Circuit depth            & $\mathcal{{O}}(m) = \mathcal{{O}}(\log N)$ \\
Boundary conditions      & essential, traction-free, mixed \\
\quad enforced by            & reflections in the unitary set \\
Verification error       & $\sim10^{{-13}}$ (see Table~\ref{{tab:verification}}) \\
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("tab_resources.tex", body)


# ---------------------------------------------------------------------------
# Table 3 - measured gate counts
# ---------------------------------------------------------------------------

def collect_gatecounts(mmax: int, mcx: bool) -> dict:
    from qiskit import transpile
    from pyblockencode.linear_circuits import LinearElasticityCircuit
    from pyblockencode.qiskit_encoding import ElasticityCircuit

    gc: dict = {}
    for m in range(2, mmax + 1):
        rec: dict = {}
        print(f"  transpiling m={m} ...", end='', flush=True)
        t0 = time.time()

        n = LinearElasticityCircuit(m=m, nu=0.3)
        tq = transpile(n.circuit(), basis_gates=BASIS, optimization_level=1)
        ops = tq.count_ops()
        rec['new_t'] = ops.get('t', 0) + ops.get('tdg', 0)
        rec['new_cx'] = ops.get('cx', 0)
        rec['new_depth'] = tq.depth()
        rec['new_qubits'] = n.num_qubits

        if mcx:
            o = ElasticityCircuit(m=m, nu=0.3)
            tq = transpile(o.circuit(), basis_gates=BASIS, optimization_level=1)
            ops = tq.count_ops()
            rec['old_t'] = ops.get('t', 0) + ops.get('tdg', 0)
            rec['old_cx'] = ops.get('cx', 0)
            rec['old_depth'] = tq.depth()
            rec['old_qubits'] = o.num_qubits

        gc[str(m)] = rec
        print(f" {time.time()-t0:.1f}s")
    return gc


def table_gatecounts(gc: dict, mcx: bool) -> None:
    ms = sorted(int(k) for k in gc)
    rows = []
    for m in ms:
        r = gc[str(m)]
        if mcx and 'old_t' in r:
            ratio = r['old_t'] / max(r['new_t'], 1)
            rows.append(
                f"${m}$ & ${2**m}$ & {thousands(r['old_t'])} & ${r['old_qubits']}$ & "
                f"{thousands(r['new_t'])} & {thousands(r['new_depth'])} & "
                f"${r['new_qubits']}$ & ${ratio:.0f}\\times$ \\\\")
        else:
            rows.append(
                f"${m}$ & ${2**m}$ & --- & --- & {thousands(r['new_t'])} & "
                f"{thousands(r['new_depth'])} & ${r['new_qubits']}$ & --- \\\\")

    body = rf"""\begin{{table*}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{6pt}}
\renewcommand{{\arraystretch}}{{1.15}}
\caption{{Measured non-Clifford cost of the elasticity block encoding ($\nu=0.3$),
after transpilation to a Clifford$+T$ basis.  ``MCX ladder'' is the incrementer
built from multi-controlled $X$ gates with $0,\dots,m-1$ controls, the
construction used in the reference implementation of Kharazi
et~al.~\cite{{kharazi2025explicit}}; ``linear'' is the prefix-AND incrementer of
Section~\ref{{sec:encoding}}, which uses $m-1$ additional ancillas.  The linear
$T$-count is exactly affine in $m$, so the $\mathcal{{O}}(\log N)$ claim is
measured rather than inherited by citation.}}
\label{{tab:gatecounts}}
\begin{{tabular}}{{@{{}}rr rr rrr r@{{}}}}
\toprule
& & \multicolumn{{2}}{{c}}{{MCX ladder}} & \multicolumn{{3}}{{c}}{{Linear incrementer}} & \\
\cmidrule(lr){{3-4}}\cmidrule(lr){{5-7}}
$m$ & $N$ & $T$ & qubits & $T$ & depth & qubits & speedup \\
\midrule
{chr(10).join(rows)}
\bottomrule
\end{{tabular}}
\end{{table*}}
"""
    write("tab_gatecounts.tex", body)


# ---------------------------------------------------------------------------
# Table 4 - verification
# ---------------------------------------------------------------------------

def collect_verification() -> list:
    from pyblockencode.linear_circuits import (
        LinearElasticityCircuit, LinearPoissonCircuit, verify_columns)

    rows = []
    cases = [("elasticity, $\\nu=0$", lambda: LinearElasticityCircuit(m=2, nu=0.0)),
             ("elasticity, $\\nu=0.3$", lambda: LinearElasticityCircuit(m=2, nu=0.3)),
             ("elasticity, $\\nu=0.45$", lambda: LinearElasticityCircuit(m=2, nu=0.45)),
             ("Poisson 1D, FDM", lambda: LinearPoissonCircuit(m=4, dim=1, disc='fdm')),
             ("Poisson 1D, FEM", lambda: LinearPoissonCircuit(m=4, dim=1, disc='fem')),
             ("Poisson 2D, FDM", lambda: LinearPoissonCircuit(m=3, dim=2, disc='fdm')),
             ("Poisson 2D, FEM", lambda: LinearPoissonCircuit(m=3, dim=2, disc='fem'))]
    for label, mk in cases:
        enc = mk()
        print(f"  verifying {label} ...", end='', flush=True)
        t0 = time.time()
        r = verify_columns(enc)
        rows.append({'label': label, 'm': enc.m, 'qubits': r['num_qubits'],
                     'N0': r['N0'], 'err': r['block_encoding_rel_err']})
        print(f" {r['block_encoding_rel_err']:.1e}  ({time.time()-t0:.1f}s)")
    return rows


def table_verification(rows: list) -> None:
    body_rows = [
        f"{r['label']} & ${r['m']}$ & ${r['N0']}$ & ${r['qubits']}$ & {sci(r['err'])} \\\\"
        for r in rows]
    body = rf"""\begin{{table}}[t]
\centering
\footnotesize
\setlength{{\tabcolsep}}{{5pt}}
\renewcommand{{\arraystretch}}{{1.15}}
\caption{{Block-encoding verification.  Each column of
$\alpha\,U[{{:}}N_0,{{:}}N_0]$ is obtained by a separate statevector simulation
and compared against the classically assembled operator; the table reports the
relative Frobenius error.  Column-wise simulation costs $2^{{n_q}}$ rather than
the $4^{{n_q}}$ of forming the dense unitary, which is what makes the larger
cases reachable.}}
\label{{tab:verification}}
\begin{{tabular}}{{@{{}}lrrrr@{{}}}}
\toprule
Operator & $m$ & $N_0$ & qubits & rel.\ error \\
\midrule
{chr(10).join(body_rows)}
\bottomrule
\end{{tabular}}
\end{{table}}
"""
    write("tab_verification.tex", body)


# ---------------------------------------------------------------------------

def main():
    ap = argparse.ArgumentParser()
    ap.add_argument('--mmax', type=int, default=6,
                    help='largest m in the gate-count table (default 6)')
    ap.add_argument('--nu', type=float, default=0.3)
    ap.add_argument('--mcx', action='store_true',
                    help='include the MCX-ladder comparison column; it is the '
                         'slow half of the run (46s at m=4, superlinear)')
    ap.add_argument('--no-verify', action='store_true',
                    help='skip the verification table (statevector sims)')
    args = ap.parse_args()

    try:
        import pyblockencode  # noqa: F401
    except ImportError:
        sys.exit("Run this from the repository root (the folder holding "
                 "pyblockencode/).")

    mcx = args.mcx

    print("LCU terms ...")
    table_lcu(args.nu)

    print("boundary treatments ...")
    table_boundary(args.nu)

    print("gate counts ...")
    if not mcx:
        print("  (MCX-ladder columns omitted; rerun with --mcx for the "
              "manuscript table)")
    gc = collect_gatecounts(args.mmax, mcx)
    table_gatecounts(gc, mcx)

    print("resources ...")
    table_resources(gc)

    if not args.no_verify:
        print("verification ...")
        table_verification(collect_verification())

    print(f"\nDone.  \\input{{tables/...}} from the manuscript.")


if __name__ == '__main__':
    main()