"""makeTables.py -- every table in the paper, written to tables/ as LaTeX.

    python makeTables.py                 all tables
    python makeTables.py tightness       just that one
    python makeTables.py --list          names and destinations

Each file holds only the `tabular`, so the surrounding `table` environment,
the caption and the label stay in main.tex where they can be edited:

    \\begin{table}[h]
    \\centering\\footnotesize
    \\caption{...}
    \\label{tab:resources}
    \\input{tables/resources}
    \\end{table}

Closed forms that appear in the paper are ASSERTED against the measured value
before they are written, so a table cannot go stale relative to the code.
"""
from __future__ import annotations

import sys
import os

import numpy as np
from qiskit import QuantumCircuit, transpile
from qiskit.circuit.library import StatePreparation

from pyblockencode import (blockencode, PeriodicBlockEncoding, BASIS,
                           I_, DI_, DZ_, DX_,
                           POISSON2D, ELASTICITY2D,
                           POISSON2D_2PHASE, ELASTICITY2D_2PHASE)

TABDIR = "tables"
BASIS = ["cx", "u"]
OPT_LEVEL = 2          # Qiskit's default; reported counts and verification use it
NU, VF, E1, E2 = 0.3, 0.25, 3.0, 1.0

CELLS = [
    ("2D scalar, homog.\\", POISSON2D("fe")),
    ("2D scalar, 2-phase", POISSON2D_2PHASE(vf=VF, E1=E1, E2=E2)),
    ("2D elast., homog.\\", ELASTICITY2D(nu=NU)),
    ("2D elast., 2-phase", ELASTICITY2D_2PHASE(nu=NU, vf=VF, E1=E1, E2=E2)),
]


def write(name: str, spec: str, header: list[str], rows: list, note="") -> None:
    """Emit one tabular. `rows` entries are lists of cells, or None for a rule."""
    os.makedirs(TABDIR, exist_ok=True)
    out = [f"% generated by makeTables.py -- do not edit{note}",
           f"\\begin{{tabular}}{{@{{}}{spec}@{{}}}}", "\\toprule"]
    out.append(" & ".join(header) + r" \\")
    out.append("\\midrule")
    for r in rows:
        if r is None:
            out.append("\\addlinespace[1pt]")
        elif r == "mid":
            out.append("\\midrule")
        else:
            out.append(" & ".join(str(c) for c in r) + r" \\")
    out += ["\\bottomrule", "\\end{tabular}", ""]
    open(f"{TABDIR}/{name}.tex", "w").write("\n".join(out))
    print(f"    {TABDIR}/{name}.tex")


def si(n: int) -> str:
    """Degrees of freedom, abbreviated."""
    if n < 1000:
        return f"${n}$"
    if n < 10 ** 6:
        return f"${n / 1000:.1f}$K"
    return f"${n / 10 ** 6:.1f}$M"


def prep_cost(be) -> tuple[int, int]:
    """(rotations, CX) of PREP_L together with PREP_R^dag."""
    vL, vR = be._prep_vectors()
    qc = QuantumCircuit(be.n_prep)
    qc.append(StatePreparation(vL), range(be.n_prep))
    sub = QuantumCircuit(be.n_prep)
    sub.append(StatePreparation(vR), range(be.n_prep))
    qc.compose(sub.inverse(), inplace=True)
    t = transpile(qc, basis_gates=BASIS, optimization_level=OPT_LEVEL)
    return t.count_ops().get("u", 0), t.count_ops().get("cx", 0)


def pauli_coeffs(K: np.ndarray) -> np.ndarray:
    """Coefficients of K over the n-qubit Pauli basis, O(4^n n)."""
    n = int(round(np.log2(K.shape[0])))
    T = np.asarray(K, dtype=complex).reshape((2,) * (2 * n))
    for q in range(n):
        T = np.moveaxis(T, (q, n + q), (0, 1))
        a, b, c, d = T[0, 0], T[0, 1], T[1, 0], T[1, 1]
        T = np.stack([(a + d) / 2, (b + c) / 2, 1j * (b - c) / 2, (a - d) / 2])
        T = T.reshape((2, 2) + T.shape[1:])
        T = np.moveaxis(T, (0, 1), (q, n + q))
    return T.ravel()


def norms(be) -> tuple[float, float]:
    K = be.reference()
    return (float(np.abs(K).sum(axis=1).max()), float(np.linalg.norm(K, 2)))


# ==========================================================================
#  Section 3.2: the Poisson cell against a Pauli expansion
# ==========================================================================
def _pauli_law(m: int) -> tuple[int, float]:
    """(L, alpha) of the exact Pauli expansion of the scalar cell at m."""
    c = pauli_coeffs(PeriodicBlockEncoding(POISSON2D("fe"), m).reference())
    return int((np.abs(c) > 1e-10).sum()), float(np.abs(c).sum())


def tab_poisson_compare(m: int = 12) -> None:
    be = PeriodicBlockEncoding(POISSON2D("fe"), m)
    L_p = int(round(9 / 16 * 4 ** m))
    a_p = m * m / 3 + 2 * m / 3 + 8 / 3
    n_p = int(np.ceil(np.log2(L_p)))
    # The two Pauli closed forms are extrapolated to m = 12, so they are
    # measured where measuring is affordable and only then extrapolated.
    for mm in (2, 3, 4):
        L_m, a_m = _pauli_law(mm)
        assert L_m == round(9 / 16 * 4 ** mm), (mm, L_m)
        assert abs(a_m - (mm * mm / 3 + 2 * mm / 3 + 8 / 3)) < 1e-9, (mm, a_m)
    _, two = norms(PeriodicBlockEncoding(POISSON2D("fe"), 5))
    _, two4 = norms(PeriodicBlockEncoding(POISSON2D("fe"), 4))
    assert abs(two4 - two) < 1e-9, "||K||_2 should be flat in m"
    r = be.resources()
    write("poisson_compare", "lrr", ["quantity", "Pauli", "shift"], [
        ["terms $L$", f"${L_p:,}$".replace(",", "{,}"), f"${be.L}$"],
        [r"\textsc{prep} ancillas", f"${n_p}$", f"${be.n_prep}$"],
        [r"\textsc{prep} rotations", f"${2 ** n_p / 10 ** 6:.0f}$M",
         f"${2 ** be.n_prep}$"],
        [r"\textsc{select} Toffoli", f"${L_p / 10 ** 6:.1f}$M", f"${r['toffoli']}$"],
        ["$\\alpha$", f"${a_p:.1f}$", f"${be.alpha:.3f}$"],
        ["$p_{\\mathrm{succ}}$", f"${(two / a_p) ** 2:.4f}$",
         f"${(two / be.alpha) ** 2:.2f}$"],
    ])
    print(f"       L_Pauli = (9/16)4^m = {L_p:,};  alpha_Pauli = {a_p:.4f} "
          f"(both measured exactly at m = 2, 3, 4, then extrapolated);  "
          f"||K||_2 = {two:.4f}, m-flat")


# ==========================================================================
#  Section 3.3: the 17 LCU terms of the homogeneous elasticity cell
# ==========================================================================
def tab_lcu(nu: float = NU) -> None:
    """Group the 17 terms, and check the closed forms against the values."""
    t = ELASTICITY2D(nu=nu).terms()
    C = 1.0 / (1 - nu ** 2)
    groups = [
        ("$I$", "$(I,I)$, the centre",
         lambda k: k[2] == DI_ and k[:2] == (I_, I_),
         r"\dfrac{2(3-\nu)}{3(1-\nu^{2})}", 2 * (3 - nu) / 3 * C),
        ("$I$", "all eight neighbours",
         lambda k: k[2] == DI_ and k[:2] != (I_, I_),
         r"-\dfrac{3-\nu}{12(1-\nu^{2})}", -(3 - nu) / 12 * C),
        ("$Z$", "$(I,S)$, $(I,S^\\dagger)$",
         lambda k: k[2] == DZ_ and k[0] == I_,
         r"+\dfrac{1}{4(1-\nu)}", +1 / (4 * (1 - nu))),
        ("$Z$", "$(S,I)$, $(S^\\dagger,I)$",
         lambda k: k[2] == DZ_ and k[1] == I_,
         r"-\dfrac{1}{4(1-\nu)}", -1 / (4 * (1 - nu))),
        ("$X$", "$(S,S^\\dagger)$, $(S^\\dagger,S)$",
         lambda k: k[2] == DX_ and k[0] != k[1],
         r"+\dfrac{1}{8(1-\nu)}", +1 / (8 * (1 - nu))),
        ("$X$", "$(S,S)$, $(S^\\dagger,S^\\dagger)$",
         lambda k: k[2] == DX_ and k[0] == k[1],
         r"-\dfrac{1}{8(1-\nu)}", -1 / (8 * (1 - nu))),
    ]
    rows, seen = [], 0
    for sig, offs, pred, closed, val in groups:
        ks = [k for k in t if pred(k)]
        assert ks, f"no terms matched {sig} {offs}"
        for k in ks:
            assert abs(t[k] - val) < 1e-12, (k, t[k], val)
        seen += len(ks)
        rows.append([sig, offs, f"${len(ks)}$", f"${closed}$", f"${val:+.4f}$"])
    assert seen == len(t) == 17, (seen, len(t))
    a = sum(abs(v) for v in t.values())
    assert abs(a - 1.0 * (33 + nu) / (6 * (1 - nu ** 2))) < 1e-12
    rows.append("mid")
    rows.append([r"\multicolumn{2}{@{}l}{$\ael = \sum_k |c_k|$}",
                 f"${len(t)}$", r"$\dfrac{E(33+\nu)}{6(1-\nu^{2})}$",
                 f"${a:.4f}$"])
    write("lcu", "llccr",
          ["$\\sigma_r$", "stencil offsets $(U^{(x)}_p, U^{(y)}_q)$", "\\#",
           "coefficient", f"$\\nu={nu}$"], rows)
    print(f"       all 17 terms matched their closed forms; "
          f"alpha = {a:.6f} = E(33+nu)/(6(1-nu^2))")


# ==========================================================================
#  Section 6: subnormalization of the two-phase elasticity cell
# ==========================================================================
def tab_alpha_el() -> None:
    rows = []
    for nu in (0.0, 0.25, 0.30, 1 / 3, 0.40, 0.45):
        A = 1.0 * (33 + nu) / (6 * (1 - nu ** 2))
        B = (69 + 5 * nu + 6 * abs(1 - 3 * nu)) / (12 * (1 - nu ** 2))
        L = len(ELASTICITY2D_2PHASE(nu=nu, vf=VF, E1=3, E2=1).terms())
        a3 = ELASTICITY2D_2PHASE(nu=nu, vf=VF, E1=3, E2=1).alpha()
        a10 = ELASTICITY2D_2PHASE(nu=nu, vf=VF, E1=10, E2=1).alpha()
        for op, want in ((ELASTICITY2D_2PHASE(nu=nu, vf=VF, E1=3, E2=1), a3),
                         (ELASTICITY2D_2PHASE(nu=nu, vf=VF, E1=10, E2=1), a10)):
            assert abs(op.alpha_published() - want) < 1e-10
        assert abs(min(3, 1) * A + abs(3 - 1) * B - a3) < 1e-10
        lab = "$1/3$" if abs(nu - 1 / 3) < 1e-9 else f"${nu:g}$"
        rows.append([lab, f"${A:.3f}$", f"${B:.3f}$", f"${L}$",
                     f"${a3:.3f}$", f"${a10:.3f}$"])
    write("alpha_el", "lrrrrr",
          ["$\\nu$", "$A(\\nu)$", "$B(\\nu)$", "$L$",
           "$\\alpha$, $E_1{=}3$", "$\\alpha$, $E_1{=}10$"], rows)
    print("       closed forms A, B and alpha = min A + |dE| B all confirmed; "
          "L = 49 at nu = 1/3, else 57")


# ==========================================================================
#  Section 7: the qubit budget
# ==========================================================================
def tab_qubits() -> None:
    rows = []
    for name, op in CELLS:
        a, b = (PeriodicBlockEncoding(op, m) for m in (4, 9))
        slope, rem = divmod(b.num_qubits - a.num_qubits, 5)
        assert rem == 0, (name, "qubit count is not affine in m")
        icept = a.num_qubits - slope * 4
        for m in range(2, 11):
            be = PeriodicBlockEncoding(op, m)
            assert be.num_qubits == slope * m + icept, (name, m)
        sysx = "$2m$" if not op.has_dof else "$2m{+}1$"
        rows.append([name, sysx, f"${a.n_prep}$", "$1$", "$m{-}1$",
                     f"$3m{{+}}{icept:.0f}$"])
    write("qubits", "lrrrrr",
          ["cell", "system", "$n_{\\mathrm{prep}}$", "sel.", "carry", "total"],
          rows)
    print("       qubit totals verified affine over m = 2..10")


# ==========================================================================
#  Section 8: resources, cost split, baseline, tightness
# ==========================================================================
def tab_resources() -> None:
    rows = []
    for j, (name, op) in enumerate(CELLS):
        if j:
            rows.append(None)
        for i, m in enumerate((4, 8, 12)):
            _, info = blockencode(op, m=m)
            rows.append([name if i == 0 else "", f"${m}$", si(info.dofs),
                         f"${info.L}$", f"${info.alpha:.2f}$",
                         f"${info.qubits}$", f"${info.toffoli}$",
                         f"${info.cx}$"])
    write("resources", "llrrrrrr",
          ["cell", "$m$", "dof", "$L$", "$\\alpha$", "qubits", "Toff.", "CX"],
          rows)


def tab_where(m: int = 12) -> None:
    rows = []
    for name, op in CELLS:
        be = PeriodicBlockEncoding(op, m)
        rot, pcx = prep_cost(be)
        tot = be.resources()["cx"]
        rows.append([name, f"${be.n_prep}$", f"${2 ** be.n_prep}$", f"${be.L}$",
                     f"${rot}$", f"${pcx}$", f"${100 * pcx / tot:.0f}\\%$"])
    write("where", "lrrrrrr",
          ["cell", "$n_{\\mathrm{prep}}$", "slots", "$L$", "rot.",
           "\\textsc{prep} CX", "share"], rows)


def tab_baseline(m: int = 4) -> None:
    rows = []
    for name, op in CELLS:
        be = PeriodicBlockEncoding(op, m)
        c = pauli_coeffs(be.reference())
        nz = int((np.abs(c) > 1e-10).sum())
        if not getattr(op, "has_refl", False):        # closed forms apply
            want = 9 / 16 * 4 ** m if not op.has_dof else 9 / 8 * 4 ** m - 1
            assert nz == round(want), (name, nz, want)
        rows.append([name, f"${be.L}$", f"${be.alpha:.2f}$", f"${nz}$",
                     f"${float(np.abs(c).sum()):.2f}$"])
    write("baseline", "lrrrr",
          [" & \\multicolumn{2}{c}{shift} & \\multicolumn{2}{c}{Pauli} \\\\\n"
           "\\cmidrule(lr){2-3}\\cmidrule(lr){4-5}\ncell",
           "$L$", "$\\alpha$", "$L$", "$\\alpha$"], rows)
    print(f"       homogeneous Pauli counts match (9/16)4^m and (9/8)4^m-1 at m = {m}")


def tab_tightness(m: int = 5) -> None:
    rows = []
    for name, op in CELLS:
        be = PeriodicBlockEncoding(op, m)
        inf, two = norms(be)
        a = be.alpha
        rows.append([name, f"${a / inf:.4f}$", f"${inf / two:.4f}$",
                     f"${a / two:.4f}$", f"${(two / a) ** 2:.3f}$"])
        lo = PeriodicBlockEncoding(op, 3)
        i2, _ = norms(lo)
        assert abs(lo.alpha / i2 - a / inf) < 1e-9, "LCU slack should be m-flat"
    write("tightness", "lrrrr",
          ["cell", "LCU slack", "norm gap",
           "$\\alpha/\\norm{\\mathbf{K}}_2$", "$p_{\\mathrm{succ}}$"], rows)
    print("       LCU slack confirmed independent of m in all four cells")


TABLES = {
    "poisson_compare": (tab_poisson_compare, "Sec. 3.2, shift against Pauli"),
    "lcu":             (tab_lcu,             "Sec. 3.3, the 17 elasticity terms"),
    "alpha_el":        (tab_alpha_el,        "Sec. 6, alpha against nu"),
    "qubits":          (tab_qubits,          "Sec. 7, qubit budget"),
    "resources":       (tab_resources,       "Sec. 8, measured resources"),
    "where":           (tab_where,           "Sec. 8, PREP against the circuit"),
    "baseline":        (tab_baseline,        "Sec. 8, Pauli baseline"),
    "tightness":       (tab_tightness,       "Sec. 8, tightness decomposition"),
}


def main(argv) -> None:
    if "--list" in argv:
        for k, (_, d) in TABLES.items():
            print(f"  {k:<17} {d}")
        return
    wanted = [a for a in argv if not a.startswith("-")] or list(TABLES)
    bad = [w for w in wanted if w not in TABLES]
    if bad:
        raise SystemExit(f"unknown table(s) {bad}; choose from {sorted(TABLES)}")
    for name in wanted:
        fn, desc = TABLES[name]
        print(f"{name}  ({desc})")
        fn()
    print("\ndone")


if __name__ == "__main__":
    main(sys.argv[1:])